[project]
name = "createthesun2"
version = "0.3.0-a"
description = "An incremental game where the goal is to create the sun!"
readme = "README.md"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.coverage.run]
source = ["createthesun"]
